# Site settings
title: Les kanců
email: info@leskancu.cz
description: >
  Jsme Les kanců, grafické studio ze Sudet.

post_address: |
  Bozděchova 4
  400 01 Ústí nad Labem
post_address_link: "https://goo.gl/maps/rltaY"
team_members:
  - name: Martina Calajová
    email: martina@leskancu.cz
    img: martina
  - name: Michal Kukačka
    email: michal@leskancu.cz
    img: michal
  - name: Lucie Zelená
    email: lucie@leskancu.cz
    img: lucie

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leskancu.cz" # the base hostname & protocol for your site
facebook_url: "https://www.facebook.com/leskancu"

# Build settings
markdown: kramdown

highlighter: pygments
safe: true
lsi: false
